version: '3'

dotenv: ['.env']

includes:
  cmp: 
    taskfile: ./components
    dir: ./components

  src:
    taskfile: ./src
    dir: ./src

  tf:
    taskfile: ./terraform
    dir: ./terraform 

  script:
    taskfile: ./scripts
    dir: ./scripts
