steps:
  - name: 'gcr.io/cloud-builders/docker:latest'
    args: [
      'build',
      '--network=cloudbuild',
      '-t',
      'asia-south2-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_TARGET_IMAGE_URI',
      '.'
    ]
    dir: 'src/job_runner'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia-south2-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_TARGET_IMAGE_URI'

timeout: 3600s

