  
version: '3'  

tasks:  
  init:
    cmds:
      - terraform init 
  
  plan:
    cmds:
      - terraform plan

  apply:
    cmds:
      - terraform apply

  destroy-all:
    cmds:
      - terraform destroy

  destroy-task-queue:
    cmds:
      - terraform destroy -target=google_cloud_tasks_queue.simple

  destroy-cloud-run-signer:
    cmds:
      - terraform destroy -target=google_cloud_run_v2_service.signer