version: '3'



tasks:
  go-run-main:
    dir: go-hello
    cmds:
      - go run main.go

  go-build-image:
    dir: go-hello
    cmds:
      - docker build -t go-hello:v2 .

  get-signed-url:
    dir: bucket
    env: 
      CLOUDSDK_PYTHON_SITEPACKAGES: "1" 
    cmds:
      - bash ./get-signed.sh

  upload-mp4:
    dir: bucket
    cmds:
      - bash ./upload.sh