version: '3'


vars:
  CONDA_ENV: gcp
  PYTHON_CMD: conda run -n {{.CONDA_ENV}} python

tasks:
  gcr-run-signer-local:
    desc: run the gcs signer fastapi server (localhost:8090) 
    cmds:
      - ./run-gcr-signer.sh