steps:
  - name: 'gcr.io/cloud-builders/docker:latest'
   #build docker image and place in artifact repo/package
    args: [
      'build',
      '--network=cloudbuild',
      '-t',
      'asia-south2-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_TARGET_IMAGE_URI',
      '.'
    ]
    dir: 'src/process_job'

options:
  #8 cpu, 8gb mem 
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia-south2-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_TARGET_IMAGE_URI'

timeout: 3600s
