

services:
  process:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: process-cont
    environment:
      - HLS_BUCKETNAME=hls-f9f45cdc
      - FILE_ID=test02908476
      - INPUT_PATH=$SIGNED_URL_GET
      - MODE=prod 


