version: '3'


tasks:
  gcs-sign-compile:
    dir: ./sign_bucket
    cmds: 
      - tsc --skipLibCheck

  gcs-sign-get:
    dir: ./sign_bucket/dist
    deps: [sign-compile]
    cmds: 
      - node sign.js

  gcr-task-worker:
    dir: ../scripts/
    cmds: 
      - ./run-gcr-tasker.sh

  process-run-dev:
    dir: ./process_job
    cmds:
      - go run main.go

  process-run-build:
    dir: ./process_job
    cmds:
      - go build -v -o processjob 
      - go run ./processjob

  process-run-test:
    dir: ./process_job
    desc: run unit tests for processjob go package
    cmds: 
      - go test -v 

  process-container-build:
    dir: ./process_job
    desc: build the process image, not rebuild all (with compose)
    cmds:
      - docker compose down
      - docker compose up -d

  process-container-rebuild:
    dir: ./process_job
    desc: rebuild the process image (with compose)
    cmds:
      - docker compose down
      - COMPOSE_BAKE=true docker compose up --build -d

  process-container-rebuild-force:
    dir: ./process_job
    desc: rebuild the process image (force-redo-all) (with compose)
    cmds:
      - docker compose down
      - COMPOSE_BAKE=true docker compose build --no-cache
      - docker compose up -d --force-recreate
 