version: '3'


tasks:
  gcr-run-signer-local:
    dir: ./sign_bucket
    cmds: 
      - ./run-gcr-signer.sh

  gcr-run-job-runner-local:
    dir: ./job_runner
    cmds:
      - ./run-job-runner.sh


  process-run-dev:
    dir: ./process_job
    cmds:
      - go run main.go

  process-run-build:
    dir: ./process_job
    cmds:
      - go build -v -o processjob 
      - go run ./processjob

  process-run-test:
    dir: ./process_job
    desc: run unit tests for processjob go package
    cmds: 
      - go test -v 

  process-container-build:
    dir: ./process_job
    desc: build the process image, not rebuild all (with compose)
    cmds:
      - docker compose down
      - docker compose up -d

  process-container-rebuild:
    dir: ./process_job
    desc: rebuild the process image (with compose)
    cmds:
      - docker compose down
      - COMPOSE_BAKE=true docker compose up --build -d

  process-container-rebuild-force:
    dir: ./process_job
    desc: rebuild the process image (force-redo-all) (with compose)
    cmds:
      - docker compose down
      - COMPOSE_BAKE=true docker compose build --no-cache
      - docker compose up -d --force-recreate

  process-container_end:
    dir: ./process_job
    cmds:
      - docker compose down

  process-dockerhub-deploy:
    dir: ./process_job
    desc: deploy the process-job container to dockerhub (arg - tag)
    cmds:
      - docker buildx build --platform linux/amd64 -t sardinesszsz/processjob:{{.CLI_ARGS}} --push .
