version: '3'


tasks:
  gcs-sign-compile:
    dir: ./sign_bucket
    cmds: 
      - tsc --skipLibCheck

  gcs-sign-get:
    dir: ./sign_bucket/dist
    deps: [sign-compile]
    cmds: 
      - node sign.js

  gcr-task-worker:
    dir: ../scripts/
    cmds: 
      - ./run-gcr-tasker.sh

  process-run-dev:
    dir: ./process_job
    cmds:
      - go run main.go

  process-run-build:
    dir: ./process_job
    cmds:
      - go build -v -o processjob 
      - go run ./processjob

  process-run-test:
    dir: ./process_job
    cmds: 
      - go test -v

  process-image-build:
    dir: ./process_job
    desc: build process-job image (pass argument - image name)
    cmds:
      - docker build -t {{.CLI_ARGS}} .